version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile.api
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn server:app --host 0.0.0.0'
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/pro_db
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pro_db
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=danila@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  postgres_data:

# docker-compose up -d --build