FROM python:3.9.7-slim

# set work directory
WORKDIR /server

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY server/requirements.txt server/
RUN pip install -r server/requirements.txt

# copy project
COPY server/ .