version: '3.8'

services:
  db:
    container_name: postg_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

#  pgadmin:
#      container_name: pgadmin
#      image: pgadmin4
#      environment:
#        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
#        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
#      ports:
#        - 5050:80
#      depends_on:
#        - db
#
#  db:
#    image: postgres:15.0do
#    expose:
#      - 5432
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=1234
#      - POSTGRES_DB=postgres
#
##    env_file:
##      - .env
##    volumes:
##      - ./fastapi_app.db:/app/fastapi_app.db:delegated
