version: '3.8'

services:
  db:
    container_name: postg_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pro_db

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      ports:
        - "5050:80"
      depends_on:
        - db
  app:
    container_name: app
    build: ..
#    --host 0.0.0.0 --port 8000
#    command: bash -c "uvicorn server:app  " #--reload
    command: uvicorn server:app --host 0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
#    environment:
#      DATABASE_URL: postgres://todoapp@postgres/todos
#
#  db:
#    image: postgres:15.0do
#    expose:
#      - 5432
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=1234
#      - POSTGRES_DB=postgres
#
##    env_file:
##      - .env
##    volumes:
##      - ./fastapi_app.db:/app/fastapi_app.db:delegated
